### ISSUE TITLE
Windows builds for smfc

### ISSUE THREAD

**Issue by crackcomm** [senior7515/smf#262]
Is there any chance you could provide smfc in githubs releases, cross compiled for windows?

**Comment by senior7515** [comment]
Yeah, that's a good point. I need to. As long as bazel works on windows, i should be able to. 

I have no idea how to do it yet tho. 

@crackcomm  do you want to take this on. ?

**Comment by senior7515** [comment]
i.e.: i probably need to find a windows CI first.

**Comment by crackcomm** [comment]
what about appveyor?

**Comment by senior7515** [comment]
will add one this week for sure. will make it easier to have contributors like yourself.

**Comment by crackcomm** [comment]
it will be actually helpful in developing further go implementation, for me, thanks 🥇

**Comment by crackcomm** [comment]
How about cross-compiling from linux using mingw?

**Comment by senior7515** [comment]
I'll try to add appveyor this weekend. I saw how to add bazel relatively straight forward. 

BTW, i think it works as is, if you want to try. AFAIK bazel should take care of all the compiler options.

https://github.com/google/brotli/blob/master/scripts/appveyor.yml#L56

Can you try it on windows via:

```
bazel build --verbose_failures --sandbox_debug //src/go/...
```

**Comment by senior7515** [comment]
where ROOT= smf top dir 

do this

```
bazel build --verbose_failures --sandbox_debug //src/smfc/...
```
to get smfc compiling
that should give you a code generator

make sure you clone recursively though. 

``` git clone --recursive github.../smf`

**Comment by crackcomm** [comment]
I just runned it pretty quick

```sh
$ bazel build --verbose_failures --sandbox_debug //src/go/...
DEBUG: C:/users/pah/_bazel_pah/otmyybd4/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:91:3:
Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest Visual C++ installed.
DEBUG: C:/users/pah/_bazel_pah/otmyybd4/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:91:3:
Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variables, eg. VS140COMNTOOLS
DEBUG: C:/users/pah/_bazel_pah/otmyybd4/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:91:3:
Auto-Configuration Warning: Looking for Visual C++ through registry
DEBUG: C:/users/pah/_bazel_pah/otmyybd4/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:91:3:
Auto-Configuration Warning: Visual C++ build tools found at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\\VC
DEBUG: C:/users/pah/_bazel_pah/otmyybd4/external/io_bazel_rules_go/go/private/sdk.bzl:84:5: warning: ignoring symlink C:\Users\Pah\go\src\gx\ipfs\Qmc5do1bC3JH73MThEgKgKkgNKLmqrvh2uaE6919yDmUaa\procfs\fixtures\self
can't load package: package github.com/google/flatbuffers/grpc/tests: C++ source files not allowed when not using cgo or SWIG: grpctest.cpp
can't load package: package github.com/google/flatbuffers/samples: C++ source files not allowed when not using cgo or SWIG: sample_binary.cpp sample_text.cpp
can't load package: package github.com/google/flatbuffers/tests: C++ source files not allowed when not using cgo or SWIG: monster_test.grpc.fb.cc test.cpp
ERROR: C:/users/pah/_bazel_pah/otmyybd4/external/io_bazel_rules_go/BUILD.bazel:18:1: every rule of type go_context_data implicitly depends upon the target '@go_sdk//:packages.txt', but this target could not be found because of: no such package '@go_sdk//': Traceback (most recent call last):
        File "C:/users/pah/_bazel_pah/otmyybd4/external/io_bazel_rules_go/go/private/sdk.bzl", line 52
                _prepare(ctx)
        File "C:/users/pah/_bazel_pah/otmyybd4/external/io_bazel_rules_go/go/private/sdk.bzl", line 85, in _prepare
                fail("failed to list standard package...")
failed to list standard packages
ERROR: C:/users/pah/_bazel_pah/otmyybd4/external/io_bazel_rules_go/BUILD.bazel:18:1: every rule of type go_context_data implicitly depends upon the target '@go_sdk//:files', but this target could not be found because of: no such package '@go_sdk//': Traceback (most recent call last):
        File "C:/users/pah/_bazel_pah/otmyybd4/external/io_bazel_rules_go/go/private/sdk.bzl", line 52
                _prepare(ctx)
        File "C:/users/pah/_bazel_pah/otmyybd4/external/io_bazel_rules_go/go/private/sdk.bzl", line 85, in _prepare
                fail("failed to list standard package...")
failed to list standard packages
ERROR: C:/users/pah/_bazel_pah/otmyybd4/external/io_bazel_rules_go/BUILD.bazel:18:1: every rule of type go_context_data implicitly depends upon the target '@go_sdk//:tools', but this target could not be found because of: no such package '@go_sdk//': Traceback (most recent call last):
        File "C:/users/pah/_bazel_pah/otmyybd4/external/io_bazel_rules_go/go/private/sdk.bzl", line 52
                _prepare(ctx)
        File "C:/users/pah/_bazel_pah/otmyybd4/external/io_bazel_rules_go/go/private/sdk.bzl", line 85, in _prepare
                fail("failed to list standard package...")
failed to list standard packages
ERROR: Analysis of target '//src/go/smf:go_default_library' failed; build aborted: Loading failed
INFO: Elapsed time: 117.793s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

I will look into it tomorrow, I'm too tired now just had quick minute to run them for you.

```sh
$ bazel build --verbose_failures --sandbox_debug //src/smfc/...
DEBUG: C:/users/pah/_bazel_pah/otmyybd4/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:91:3:
Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest Visual C++ installed.
DEBUG: C:/users/pah/_bazel_pah/otmyybd4/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:91:3:
Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variables, eg. VS140COMNTOOLS
DEBUG: C:/users/pah/_bazel_pah/otmyybd4/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:91:3:
Auto-Configuration Warning: Looking for Visual C++ through registry
DEBUG: C:/users/pah/_bazel_pah/otmyybd4/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:91:3:
Auto-Configuration Warning: Visual C++ build tools found at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\\VC
INFO: Analysed 2 targets (0 packages loaded).
INFO: Found 2 targets...
ERROR: C:/users/pah/_bazel_pah/otmyybd4/external/third_party_flatbuffers/BUILD:54:1: C++ compilation of rule '@third_party_flatbuffers//:flatc_library' failed (Exit 2): cl.exe failed: error executing command
  cd C:/users/pah/_bazel_pah/otmyybd4/execroot/__main__
  SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\ATLMFC\include;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include;C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt
    SET LIB=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\ATLMFC\lib\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\lib\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.17134.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.17134.0\um\x64;
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\\x64;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\;C:\Program Files (x86)\Windows Kits\10\bin\10.0.17134.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\\MSBuild\15.0\bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\;;C:\WINDOWS\system32
    SET PWD=/proc/self/cwd
    SET TEMP=C:\Users\Pah\AppData\Local\Temp
    SET TMP=C:\Users\Pah\AppData\Local\Temp
  C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.14.26428/bin/HostX64/x64/cl.exe /c external/third_party_flatbuffers/src/code_generators.cpp /Fobazel-out/x64_windows-fastbuild/bin/external/third_party_flatbuffers/_objs/flatc_library/external/third_party_flatbuffers/src/code_generators.o /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /bigobj /Zm500 /J /Gy /GF /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /Iexternal/third_party_flatbuffers /Ibazel-out/x64_windows-fastbuild/genfiles/external/third_party_flatbuffers /Iexternal/bazel_tools /Ibazel-out/x64_windows-fastbuild/genfiles/external/bazel_tools /Iexternal/third_party_flatbuffers/grpc /Ibazel-out/x64_windows-fastbuild/genfiles/external/third_party_flatbuffers/grpc /Ibazel-out/x64_windows-fastbuild/bin/external/third_party_flatbuffers/grpc /Iexternal/third_party_flatbuffers/include /Ibazel-out/x64_windows-fastbuild/genfiles/external/third_party_flatbuffers/include /Ibazel-out/x64_windows-fastbuild/bin/external/third_party_flatbuffers/include /showIncludes /MD /Od /Z7 /DDEBUG -Wno-implicit-fallthrough -linclude
cl : Command line error D8021 : invalid numeric argument '/Wno-implicit-fallthrough'
INFO: Elapsed time: 0.450s, Critical Path: 0.07s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

This is all on Windows 10 Pro, Go installed.

I've never compiled C++ on windows I would appreciate any basic help on what toolchain to install if you've got any idea, on where to find this mysterious Microsoft C++ compiler?

**Comment by crackcomm** [comment]
I think before I install C++ compiler I can test Go compiling without it, seems like missing C++ compiler is reason of both errors.

**Comment by senior7515** [comment]
if that works, i'd love to get a PR with that.

**Comment by crackcomm** [comment]
under investigation ;) following were found:

1. needs boost build for mingw
2. needs zlib build for mingw

currently stopped on 

```
g++: error: unrecognized command line option ‘-mthreads’
```

**Comment by senior7515** [comment]
btw, i added an appveyor account and got stuck on bazel rules go having an issue w/ go 

https://ci.appveyor.com/project/senior7515/smf

If you fork master, it should at least give you the basic template to fiddle arround and it will automatically build on windows. check it out.

**Comment by senior7515** [comment]
https://github.com/bazelbuild/rules_go/issues/1587 - here is the upstream i think issue - not sure yet.

**Comment by senior7515** [comment]
I'd love to take in a cmake patch for this. 
I don't have a system to test. 
We can reopen when we have time after finishing Go and Java.
